### ISSUE TITLE
Add loop limit option to autorun.py

### ISSUE THREAD

**Issue by HjOtal-1** [jraynolds/Glimmer-and-Gloom#6]
To achieve 75kt, you'll need to do about 19 times, and autorun.py won't stop even after you've done 75kt so say... you accidentally left the script on like an oven, that script will keep going until you do the failstate or take G&G out of the screen.

I was wondering if it's possible to add a loop option so that autorun.py will only do 19 runs and then stop after the 75kt have been achieved, no more "oh god, I left the script on" moments.

**Comment by Jwnw1234** [comment]
quick question. did you ever run into the NoneType issue? if so, how did you fix it?

**Comment by HjOtal-1** [comment]
IIRC, I had to set Confidence to 8 (use Notepad++ or jsut normal Notepad to change that), then make sure that the glimmer, gloom, and play use shots directly from my screen, then play on a dual window display (drag one window to the very left or right of the screen and it will prompt that option).

If Confidence on 8 doesn't do it, you'll have to keep going down until it eventually works.

**Comment by jraynolds** [comment]
Thanks for the in-depth explanation, @HjOtal-1! I think limiting the loop is a good idea. I've edited the script to, by default, run 20 times.
